---
title: "Stats Final Project"
author: "Lenka and Nina"
date: "2022-12-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(fastDummies)
library(glmnet)
library(broom)
library(pscl)
library(xtable)
library(cluster)
library(factoextra)
library(lme4)
library(sjPlot)

select <- dplyr::select
```

# Recidivism Project

## Loading Data

```{r cars}
data = read.csv("NIJ_s_Recidivism_Challenge_Full_Dataset.csv")
```

## Pre-processing

data viz

```{r}
head(data,10)
```

```{r}
### Investigate missing values
data_cleaned <- data %>%
  mutate_all(~na_if(., ''))

# Column-wise
#colSums(is.na(data_cleaned)) 

# Row-wise
#summary((rowSums(is.na(data_cleaned))))

# Investigate missing drug test data
#missing_drug_tests <- data_cleaned %>% filter(is.na(DrugTests_THC_Positive) | is.na(DrugTests_Meth_Positive))
#colSums(is.na(missing_drug_tests))

# Investigate missing Jobs data 
#missing_jobs <- data_cleaned %>% filter(is.na(Jobs_Per_Year))
#colSums(is.na(missing_jobs))

# For now just drop NAs
#data_cleaned <- data_cleaned %>%
#  na.omit() # removes almost half of our observations but data set still very large (note that this removes all entries for females)
```

```{r}
### Resolve missing data 

# Categorical vars
data_cleaned <- data_cleaned %>%
  mutate(Gang_Affiliated = ifelse(Gender == "F", "false", Gang_Affiliated),
         Supervision_Risk_Score_First = ifelse(is.na(Supervision_Risk_Score_First), "missing",   Supervision_Risk_Score_First),
         Supervision_Level_First = ifelse(is.na(Supervision_Level_First), "missing", Supervision_Level_First),
         Prison_Offense = ifelse(is.na(Prison_Offense), "missing", Prison_Offense))

```

```{r}
# Remove 'DrugTest' vars (significant proportion is missing)
data_cleaned <- data_cleaned %>%
  dplyr::select(-c(DrugTests_Cocaine_Positive, DrugTests_Meth_Positive, DrugTests_Other_Positive,   Avg_Days_per_DrugTest,DrugTests_THC_Positive))
  
# Replace missing jobs data with values 0
data_cleaned <- data_cleaned %>%
  mutate(Percent_Days_Employed = ifelse(is.na(Percent_Days_Employed), 0, Percent_Days_Employed),
         Jobs_Per_Year = ifelse(is.na(Jobs_Per_Year), 0, Jobs_Per_Year))

#colSums(is.na(data_cleaned)) 
```

```{r}
### Set up dependent var and covariate matrix
y <- data_cleaned %>%
  dplyr::select(Recidivism_Within_3years) %>%
  mutate(Recidivism_Within_3years = ifelse(Recidivism_Within_3years == "true", 1, 0)) %>%
  as.matrix()%>%
  as.integer()

# 8423 observations correspond to a reoffence within three years
#sum(y$Recidivism_Within_3years)/length(y)

### Covariate matrix - removed supervision_risk_score as this is what we're trying to predict
X <- data_cleaned %>%
  rename(Age = Age_at_Release, Residence = Residence_PUMA, Supervision_Level = Supervision_Level_First) %>%
  dplyr::select(-c(ID, Recidivism_Arrest_Year1, Recidivism_Arrest_Year2, Recidivism_Arrest_Year3, Training_Sample,Recidivism_Within_3years, Supervision_Risk_Score_First)) 

# dummy col 
#dummy_colnames <- X %>% select(-c(Avg_Days_per_DrugTest, DrugTests_THC_Positive,DrugTests_Cocaine_Positive, DrugTests_Meth_Positive, DrugTests_Other_Positive, Percent_Days_Employed, Jobs_Per_Year)) %>%
#  names()

# Rename vars
colnames(X) <- gsub("Episodes_","",colnames(X))  

dummy_colnames <- X %>% select(-c(Percent_Days_Employed, Jobs_Per_Year)) %>%
 names()

X <- dummy_cols(X, select_columns = dummy_colnames, remove_first_dummy = TRUE, remove_selected_columns = TRUE)

#X <- model.matrix(~., data = X)

```

### Attempt Clustering

See: <https://towardsdatascience.com/clustering-datasets-having-both-numerical-and-categorical-variables-ed91cdca0677>

```{r}
as.data.frame(X)
```

```{r}
### Attempt clustering of mixed variable types using Gower distance metric
categorical_colnames <- as.data.frame(X) %>% dplyr::select(-c(Percent_Days_Employed, Jobs_Per_Year)) %>%
  names()

# categorical vars need to be factors
X_clustering <- X %>%
  mutate_at(categorical_colnames, as.factor) 

# could only handle

```

```{r}
#gower_df <- daisy(X_clustering, metric = "gower")
gower_df<- load("gower.Rdata")
summary(gower_df)
```

```{r}
#save(gower_df, file = "gower.Rdata")
```

```{r}
### Choose optimal number of clusters using the 'Silhouette width'
silhouette <- c()
silhouette = c(silhouette, NA)
for(i in 1:5){
  pam_clusters = pam(as.matrix(gower_df),
                 diss = TRUE,
                 k = i)
  silhouette = c(silhouette ,pam_clusters$silinfo$avg.width)
}
plot(1:10, silhouette,
     xlab = "Clusters",
     ylab = "Silhouette Width")
lines(1:10, silhouette)
```

```{r}
K3 <- pam(as.matrix(gower_df),
                 diss = TRUE,
                 k = 3)
```

```{r}
fviz_silhouette(K3, label = FALSE, print.summary = TRUE)

```

```{r}
plot(1:5, silhouette,
     xlab = "Clusters",
     ylab = "Silhouette Width")
lines(1:5, silhouette)
```

```{r}
library(janitor)

```

### Hierarchical Model

```{r}
colnames(X) <- make_clean_names(colnames(X))


#MLexamp.9 <- lmer(y ~ gender + race + social + (1+open|school/class), data=lmm.data)
#display(MLexamp.9)
#la <- model.matrix(y~., data = X)

#la
# These are the variable names:
measurevar <- "y"
groupvars  <- c(colnames(X))

# This creates the appropriate string:
paste(measurevar, paste(groupvars, collapse=" + "), sep=" ~ ")
#> [1] "y ~ x1 + x2 + x3"

# This returns the formula:
as.formula(paste(measurevar, paste(groupvars, collapse=" + "), sep=" ~ "))
#> y ~ x1 + x2 + x3
#> 



```

```{r}
X <- data_cleaned %>%
  rename(Age = Age_at_Release, Residence = Residence_PUMA, Supervision_Level = Supervision_Level_First) %>%
  dplyr::select(-c(ID, Recidivism_Arrest_Year1, Recidivism_Arrest_Year2, Recidivism_Arrest_Year3, Training_Sample,Recidivism_Within_3years, Supervision_Risk_Score_First)) 

colnames(X) <- gsub("Episodes_","",colnames(X))  

```

```{r}
X$Residence <-as.factor(X$Residence)
```

```{r}
hlm <- glmer(y ~ Gender + Residence + Race + Age + Supervision_Level+Education_Level+ (1|Gang_Affiliated), data=X, family = 'binomial')
```

```{r}
summary(hlm, corr = FALSE)
#plot_model(hlm, type = "std")
plot_model(hlm, type = "re")

```

```{r}
plot_model(hlm, type = "est")
```

```{r}
hlmnew <- glmer(y ~ Gender + Gang_Affiliated + Race  + Age+ (1|Residence), data=X, family = 'binomial')
```

```{r}
summary(hlmnew, corr = FALSE)
plot_model(hlmnew, type = "std")
plot_model(hlmnew, type = "re")
```
